// @ts-expect-error `.open-next/worker.js` is generated by `npm run build:cloudflare`.
import { default as handler } from "./.open-next/worker.js";

type Env = {
  CONTENT_AUTOMATION_TOKEN?: string;
  CRM_APP_URL?: string;
  DB?: D1Database;
  BUCKET?: R2Bucket;
};

type OpenNextHandler = {
  fetch(request: Request, env: Env, ctx: ExecutionContext): Response | Promise<Response>;
};

const openNext = handler as OpenNextHandler;

function appUrl(env: Env) {
  return (env.CRM_APP_URL || "https://fbshv-crm.ngchihuy.workers.dev").replace(/\/$/, "");
}

async function callInternalApi(env: Env, ctx: ExecutionContext, path: string, body: Record<string, unknown>) {
  const token = env.CONTENT_AUTOMATION_TOKEN || "";
  if (!token) {
    return new Response(JSON.stringify({ success: false, error: "CONTENT_AUTOMATION_TOKEN_REQUIRED" }), { status: 500 });
  }
  const request = new Request(`${appUrl(env)}${path}`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${token}`
    },
    body: JSON.stringify(body)
  });
  return openNext.fetch(request, env, ctx);
}

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return openNext.fetch(request, env, ctx);
  },

  async scheduled(event: ScheduledController, env: Env, ctx: ExecutionContext) {
    // NEO: Cron chi kich hoat ke hoach va publish-due; logic san pham/anh van nam trong CRM API.
    if (event.cron === "15 17 * * *") {
      ctx.waitUntil(callInternalApi(env, ctx, "/api/content/auto-daily", { dryRun: false }));
    }
    if (event.cron === "*/10 * * * *") {
      ctx.waitUntil(callInternalApi(env, ctx, "/api/content/publish-due", { limit: 20 }));
    }
    if (event.cron === "*/1 * * * *") {
      // NEO: Integration jobs chạy ngắn trong lifecycle cron, không dùng Worker long-running.
      ctx.waitUntil(callInternalApi(env, ctx, "/api/settings/integration-jobs", { maxJobs: 10, maxRuntimeMs: 25000 }));
    }
  }
} satisfies ExportedHandler<Env>;
