name = "fbshv-crm"
main = "custom-worker.ts"
compatibility_date = "2026-05-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "fbshv_crm_db"
database_id = "218d0eab-7734-4fda-91b9-e3e2604e6c86"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "fbshv-crm-assets"

[triggers]
crons = ["*/1 * * * *", "*/10 * * * *", "15 17 * * *"]

[vars]
CONTENT_AUTOMATION_UI_ENABLED = "true"
AUTO_PUBLISH_POSTS_ENABLED = "true"

